sudo: false
services:
    - mongodb
before_script:
    - sleep 15
script: coverage run --source=auth -m pytest -vs tests.py
language: python
arch:
  - arm64
  - amd64
python:
    - 3.8

before_install:
  - pip install codecov
after_success:
  - coverage report -m
  - codecov
